<?php

namespace Medicine\TrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MedInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedInfoRepository extends EntityRepository
{
}
